In [34]:
import cv2
import numpy as np

In [35]:
pic1 =cv2.imread('jamie.jpg')
cv2.imshow('jamie', pic1)
cv2.waitKey()
cv2.destroyAllWindows()

In [36]:
model = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [37]:
faces = model.detectMultiScale(pic1)
x1 = faces[0][0]
y1 = faces[0][1]
x2 = x1 + faces[0][2]
y2 = y1 + faces[0][3]
print(faces)
print(f" {x1}, {x2}, {y1}, {y2}")         
jamie_face = cv2.rectangle(pic1, (x1,y1) , (x2,y2), [255,255,255], 2)     
cv2.imshow("image", jamie_face)
cv2.waitKey()
cv2.destroyAllWindows()

[[274 127 357 357]
 [467 530 131 131]]
 274, 631, 127, 484


In [38]:
pic2 =cv2.imread('dakota.jpg')
cv2.imshow('dakota', pic2)
cv2.waitKey()
cv2.destroyAllWindows()

In [39]:
faces1 = model.detectMultiScale(pic2)
x1 = faces1[0][0]
y1 = faces1[0][1]
x2 = x1 + faces1[0][2]
y2 = y1 + faces1[0][3]
print(faces1)
print(f" {x1}, {x2}, {y1}, {y2}")

[[118  89 214 214]]
 118, 332, 89, 303


In [40]:
#show pic2
cv2.imshow("dakota", pic2)
cv2.waitKey()
cv2.destroyAllWindows()

In [41]:
#swap the pics
swap = pic1[214:402, 335:523]
pic2[72:260, 100:288] = swap
cv2.imshow("Swapped image", pic2)
cv2.waitKey()
cv2.destroyAllWindows()
